language: python
python:
  - "3.6"
cache: pip
install:
  - pip install numpy
  - pip install SimpleITK
script:
  - python -m unittest discover -p "*_test.py" -v
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always